[package]
name = "deki"
version = "0.4.0"
edition = "2024"

authors = ["Dekirisu <dekirisu@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A base for most of my rust projects (tailored to myself)!"
repository = "https://github.com/dekirisu/deki-rs/"
documentation = "https://docs.rs/deki"
categories = ["development-tools", "utilities"]
keywords = ["utility", "macros", "helpers"]

[dependencies]
deki_core.workspace = true
deki_macros.workspace = true
deki_proc = { workspace = true, optional = true }

[workspace.dependencies.deki_core]
path = "crates/core"
version = "0.3.0"
default-features = false

[workspace.dependencies.deki_macros]
path = "crates/macros"
version = "0.3.0"

[workspace.dependencies.deki_proc]
path = "crates/proc"
version = "0.3.0"

[workspace.dependencies]
quote = "1.0"
syn = "2.0"
proc-macro2 = "1.0"
maflow = "0.1"
extension-traits = "2.0.0"

[features]
default = ["random","approx","lerp"]
random = ["deki_core/random"]
approx = ["deki_core/approx"]
lerp = ["deki_core/lerp"]
proc = ["deki_proc"]

[workspace]
members = ["crates/*", "crates/proc"]
