[package]
name = "deki"
version = "0.3.0"
edition = "2024"

authors = ["Dekirisu <dekirisu@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A base for most of my rust projects (tailored to myself)!"
repository = "https://github.com/dekirisu/deki-rs/"

[dependencies]
deki_core.workspace = true
deki_macros.workspace = true

[workspace.dependencies.deki_core]
path = "crates/core"
version = "0.2.0"
default-features = false

[workspace.dependencies.deki_macros]
path = "crates/macros"
version = "0.2.0"

[workspace.dependencies]
quote = "1.0"
syn = "2.0"
proc-macro2 = "1.0"

[features]
default = ["random","approx","lerp"]
random = ["deki_core/random"]
approx = ["deki_core/approx"]
lerp = ["deki_core/lerp"]
proc = ["deki_core/proc"]

[workspace]
members = ["crates/*"]
