[package]
name = "deki_derive"
version = "0.1.0"
edition = "2021"

authors = ["Dekirisu <dekirisu@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "proc-macro for deki!"
repository = "https://github.com/dekirisu/deki-rs/"

[lib]
proc-macro = true

[dependencies]
derive_preset = "0.1" 
