[package]
name = "deki_macros"
version = "0.2.0"
edition = "2021"

authors = ["Dekirisu <dekirisu@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A growing set of macros (tailored to myself)!"
repository = "https://github.com/dekirisu/deki-rs/"

[lib]
proc-macro = true

[dependencies]
deki_core = { workspace = true, features = ["proc"] }
derive_preset = "0.1"
convert_case.workspace = true
paste = "1.0"
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true
